/**
 * Catalogue complet des produits DIAK-SERVICE
 * Chaque produit est associé à :
 *  - image  : chemin dans /public/images
 *  - category : clé de catégorie (voir CATEGORIES)
 *  - nameFr / nameEn : nom bilingue du produit
 *  - descFr / descEn : description courte bilingue
 *  - priceFr / priceEn : étiquette de prix bilingue
 */

// ── Clés de catégories ──────────────────────────────────────────────────────
export const CATEGORIES = {
  computers: {
    key: 'computers',
    labelFr: 'Ordinateurs',
    labelEn: 'Computers',
    searchKeywordsFr: ['ordinateur', 'pc', 'laptop', 'portable', 'bureau', 'desktop', 'workstation', 'chromebook'],
    searchKeywordsEn: ['computer', 'pc', 'laptop', 'desktop', 'workstation', 'chromebook'],
  },
  printers: {
    key: 'printers',
    labelFr: 'Imprimantes',
    labelEn: 'Printers',
    searchKeywordsFr: ['imprimante', 'imprimer', 'encre', 'laser', 'photocopieur', 'scanner', 'relier', 'reliure'],
    searchKeywordsEn: ['printer', 'ink', 'laser', 'photocopier', 'scanner', 'binding'],
  },
  accessories: {
    key: 'accessories',
    labelFr: 'Accessoires Informatiques',
    labelEn: 'Computer Accessories',
    searchKeywordsFr: ['accessoire', 'souris', 'clavier', 'adaptateur', 'usb', 'bluetooth', 'antivirus', 'projecteur', 'camera', 'appareil', 'vidéo'],
    searchKeywordsEn: ['accessory', 'mouse', 'keyboard', 'adapter', 'usb', 'bluetooth', 'antivirus', 'projector', 'camera'],
  },
  stationery: {
    key: 'stationery',
    labelFr: 'Fournitures & Papeterie',
    labelEn: 'Stationery & Supplies',
    searchKeywordsFr: ['papeterie', 'fourniture', 'bloc', 'classeur', 'cahier', 'cachet', 'tampon', 'cube'],
    searchKeywordsEn: ['stationery', 'supply', 'notebook', 'binder', 'stamp', 'block', 'cube'],
  },
  furniture: {
    key: 'furniture',
    labelFr: 'Mobilier de Bureau',
    labelEn: 'Office Furniture',
    searchKeywordsFr: ['mobilier', 'meuble', 'bureau', 'chaise', 'table', 'armoire', 'fauteuil', 'rangement', 'banquette'],
    searchKeywordsEn: ['furniture', 'desk', 'chair', 'table', 'cabinet', 'storage', 'armchair', 'bench'],
  },
};

// ── Catalogue produits ──────────────────────────────────────────────────────
export const PRODUCTS = [

  // ── ORDINATEURS ────────────────────────────────────────────────────────────
  {
    id: 'ord-1',
    image: '/images/ordinateur 1.jpeg',
    category: 'computers',
    nameFr: 'Ordinateur Portable',
    nameEn: 'Laptop',
    descFr: 'Ordinateur portable performant pour le travail et les études',
    descEn: 'High-performance laptop for work and studies',
    priceFr: 'À partir de 350 000 FCFA',
    priceEn: 'From 350,000 FCFA',
  },
  {
    id: 'ord-2',
    image: '/images/ordinateur 2.jpeg',
    category: 'computers',
    nameFr: 'PC de Bureau',
    nameEn: 'Desktop PC',
    descFr: 'PC de bureau complet pour professionnels et entreprises',
    descEn: 'Complete desktop PC for professionals and businesses',
    priceFr: 'À partir de 280 000 FCFA',
    priceEn: 'From 280,000 FCFA',
  },
  {
    id: 'ord-3',
    image: '/images/ordinateur 3.jpeg',
    category: 'computers',
    nameFr: 'Ordinateur Portable Professionnel',
    nameEn: 'Professional Laptop',
    descFr: 'Laptop professionnel haute performance, idéal pour les entreprises',
    descEn: 'High-performance professional laptop, ideal for businesses',
    priceFr: 'À partir de 380 000 FCFA',
    priceEn: 'From 380,000 FCFA',
  },
  {
    id: 'ord-4',
    image: '/images/ordinateur 4.jpeg',
    category: 'computers',
    nameFr: 'PC Tout-en-un',
    nameEn: 'All-in-One PC',
    descFr: 'PC tout-en-un compact, écran intégré, économise la place',
    descEn: 'Compact all-in-one PC with integrated screen, saves space',
    priceFr: 'À partir de 320 000 FCFA',
    priceEn: 'From 320,000 FCFA',
  },
  {
    id: 'ord-5',
    image: '/images/ordinateur 5.jpeg',
    category: 'computers',
    nameFr: 'Workstation',
    nameEn: 'Workstation',
    descFr: 'Station de travail puissante pour les professionnels exigeants',
    descEn: 'Powerful workstation for demanding professionals',
    priceFr: 'Sur devis',
    priceEn: 'On request',
  },
  {
    id: 'ord-6',
    image: '/images/ordinateur 6.jpeg',
    category: 'computers',
    nameFr: 'Mini PC',
    nameEn: 'Mini PC',
    descFr: 'Mini ordinateur compact, silencieux et économique',
    descEn: 'Compact, silent and energy-efficient mini computer',
    priceFr: 'À partir de 180 000 FCFA',
    priceEn: 'From 180,000 FCFA',
  },
  {
    id: 'ord-7',
    image: '/images/ordinateur 7.jpeg',
    category: 'computers',
    nameFr: 'Ordinateur Portable Gaming',
    nameEn: 'Gaming Laptop',
    descFr: 'Laptop gaming avec carte graphique dédiée pour les jeux et la création',
    descEn: 'Gaming laptop with dedicated graphics card for games and creation',
    priceFr: 'À partir de 450 000 FCFA',
    priceEn: 'From 450,000 FCFA',
  },
  {
    id: 'ord-8',
    image: '/images/ordinateur 8.jpg',
    category: 'computers',
    nameFr: 'PC de Bureau Complet',
    nameEn: 'Complete Desktop PC',
    descFr: 'Unité centrale complète avec écran, clavier et souris inclus',
    descEn: 'Complete desktop unit with screen, keyboard and mouse included',
    priceFr: 'À partir de 350 000 FCFA',
    priceEn: 'From 350,000 FCFA',
  },
  {
    id: 'ord-10',
    image: '/images/ordinateur 10.jpeg',
    category: 'computers',
    nameFr: 'Chromebook',
    nameEn: 'Chromebook',
    descFr: 'Chromebook léger et rapide, parfait pour l\'école et le bureau',
    descEn: 'Light and fast Chromebook, perfect for school and office',
    priceFr: 'À partir de 200 000 FCFA',
    priceEn: 'From 200,000 FCFA',
  },

  // ── IMPRIMANTES ─────────────────────────────────────────────────────────────
  {
    id: 'imp-1',
    image: '/images/imprimente 1.jpeg',
    category: 'printers',
    nameFr: 'Imprimante Jet d\'encre',
    nameEn: 'Inkjet Printer',
    descFr: 'Imprimante jet d\'encre couleur, idéale pour les photos et documents',
    descEn: 'Color inkjet printer, ideal for photos and documents',
    priceFr: 'À partir de 85 000 FCFA',
    priceEn: 'From 85,000 FCFA',
  },
  {
    id: 'imp-2',
    image: '/images/imprimente 2.jpeg',
    category: 'printers',
    nameFr: 'Imprimante Laser',
    nameEn: 'Laser Printer',
    descFr: 'Imprimante laser noir & blanc, rapide et économique pour les bureaux',
    descEn: 'Black & white laser printer, fast and cost-effective for offices',
    priceFr: 'À partir de 120 000 FCFA',
    priceEn: 'From 120,000 FCFA',
  },
  {
    id: 'imp-3',
    image: '/images/imprimente 3.jpeg',
    category: 'printers',
    nameFr: 'Imprimante Multifonction',
    nameEn: 'Multifunction Printer',
    descFr: 'Imprimante multifonction : impression, scan, copie en un seul appareil',
    descEn: 'Multifunction printer: print, scan, copy in one device',
    priceFr: 'À partir de 150 000 FCFA',
    priceEn: 'From 150,000 FCFA',
  },
  {
    id: 'imp-4',
    image: '/images/imprimente 4.jpeg',
    category: 'printers',
    nameFr: 'Photocopieur',
    nameEn: 'Photocopier',
    descFr: 'Photocopieur professionnel haute vitesse pour les entreprises',
    descEn: 'High-speed professional photocopier for businesses',
    priceFr: 'Sur devis',
    priceEn: 'On request',
  },
  {
    id: 'encre-1',
    image: '/images/encre imprimente.jpeg',
    category: 'printers',
    nameFr: 'Cartouches d\'encre',
    nameEn: 'Ink Cartridges',
    descFr: 'Cartouches d\'encre compatibles pour toutes marques d\'imprimantes',
    descEn: 'Compatible ink cartridges for all printer brands',
    priceFr: 'À partir de 8 000 FCFA',
    priceEn: 'From 8,000 FCFA',
  },
  {
    id: 'rel-1',
    image: '/images/machine pour reluire A3 et A4.jpeg',
    category: 'printers',
    nameFr: 'Machine à Relier A3/A4',
    nameEn: 'A3/A4 Binding Machine',
    descFr: 'Machine à relier les documents A3 et A4, pour un rendu professionnel',
    descEn: 'A3 and A4 document binding machine for a professional finish',
    priceFr: 'À partir de 45 000 FCFA',
    priceEn: 'From 45,000 FCFA',
  },

  // ── ACCESSOIRES INFORMATIQUES ───────────────────────────────────────────────
  {
    id: 'acc-1',
    image: '/images/adaptateur type C.jpeg',
    category: 'accessories',
    nameFr: 'Adaptateur USB Type-C',
    nameEn: 'USB Type-C Adapter',
    descFr: 'Adaptateur USB Type-C multi-port, compatible laptops et smartphones',
    descEn: 'Multi-port USB Type-C adapter, compatible with laptops and smartphones',
    priceFr: 'À partir de 6 000 FCFA',
    priceEn: 'From 6,000 FCFA',
  },
  {
    id: 'acc-2',
    image: '/images/adaptateur.jpeg',
    category: 'accessories',
    nameFr: 'Adaptateur Multi-port',
    nameEn: 'Multi-port Adapter',
    descFr: 'Hub adaptateur multi-port USB, HDMI et réseau',
    descEn: 'Multi-port hub adapter USB, HDMI and network',
    priceFr: 'À partir de 10 000 FCFA',
    priceEn: 'From 10,000 FCFA',
  },
  {
    id: 'acc-3',
    image: '/images/Anti-virus.jpeg',
    category: 'accessories',
    nameFr: 'Antivirus',
    nameEn: 'Antivirus Software',
    descFr: 'Logiciel antivirus pour protéger votre ordinateur contre les menaces',
    descEn: 'Antivirus software to protect your computer against threats',
    priceFr: 'À partir de 15 000 FCFA',
    priceEn: 'From 15,000 FCFA',
  },
  {
    id: 'acc-4',
    image: '/images/souris bluetooth rechargable.jpeg',
    category: 'accessories',
    nameFr: 'Souris Bluetooth Rechargeable',
    nameEn: 'Rechargeable Bluetooth Mouse',
    descFr: 'Souris sans fil Bluetooth rechargeable, silencieuse et ergonomique',
    descEn: 'Rechargeable Bluetooth wireless mouse, silent and ergonomic',
    priceFr: 'À partir de 12 000 FCFA',
    priceEn: 'From 12,000 FCFA',
  },
  {
    id: 'acc-5',
    image: '/images/Appareil-numerique-kodak.jpeg',
    category: 'accessories',
    nameFr: 'Appareil Photo Numérique Kodak',
    nameEn: 'Kodak Digital Camera',
    descFr: 'Appareil photo numérique Kodak, compact et facile à utiliser',
    descEn: 'Kodak digital camera, compact and easy to use',
    priceFr: 'À partir de 90 000 FCFA',
    priceEn: 'From 90,000 FCFA',
  },
  {
    id: 'acc-6',
    image: '/images/video-projecteur.jpeg',
    category: 'accessories',
    nameFr: 'Vidéo Projecteur',
    nameEn: 'Video Projector',
    descFr: 'Vidéoprojecteur pour salles de réunion, présentations et cinéma',
    descEn: 'Video projector for meeting rooms, presentations and home cinema',
    priceFr: 'À partir de 200 000 FCFA',
    priceEn: 'From 200,000 FCFA',
  },

  // ── FOURNITURES & PAPETERIE ─────────────────────────────────────────────────
  {
    id: 'pap-1',
    image: '/images/bloc-cube-complet-1.jpeg',
    category: 'stationery',
    nameFr: 'Bloc Cube Complet',
    nameEn: 'Complete Cube Block',
    descFr: 'Bloc cube avec notes, trombones et stylos, idéal pour le bureau',
    descEn: 'Cube block with notes, clips and pens, ideal for the office',
    priceFr: 'À partir de 3 500 FCFA',
    priceEn: 'From 3,500 FCFA',
  },
  {
    id: 'pap-2',
    image: '/images/bloc-cube-complet.jpeg',
    category: 'stationery',
    nameFr: 'Bloc Notes Cube',
    nameEn: 'Cube Notepad',
    descFr: 'Bloc notes cube 500 feuilles, pratique pour prendre des notes rapides',
    descEn: '500-sheet cube notepad, handy for quick notes',
    priceFr: 'À partir de 2 000 FCFA',
    priceEn: 'From 2,000 FCFA',
  },
  {
    id: 'pap-3',
    image: '/images/cachet rond automatique.jpeg',
    category: 'stationery',
    nameFr: 'Cachet Rond Automatique',
    nameEn: 'Automatic Round Stamp',
    descFr: 'Tampon encreur automatique rond, personnalisable pour entreprises',
    descEn: 'Automatic round ink stamp, customizable for businesses',
    priceFr: 'À partir de 15 000 FCFA',
    priceEn: 'From 15,000 FCFA',
  },
  {
    id: 'pap-4',
    image: '/images/classeur chrono.jpeg',
    category: 'stationery',
    nameFr: 'Classeur Chrono',
    nameEn: 'Chrono Binder',
    descFr: 'Classeur chronologique pour l\'archivage et l\'organisation de documents',
    descEn: 'Chronological binder for archiving and organizing documents',
    priceFr: 'À partir de 4 000 FCFA',
    priceEn: 'From 4,000 FCFA',
  },

  // ── MOBILIER DE BUREAU ──────────────────────────────────────────────────────
  {
    id: 'mob-1',
    image: '/images/Armoire-rangement-metalique.jpeg',
    category: 'furniture',
    nameFr: 'Armoire de Rangement Métallique',
    nameEn: 'Metal Storage Cabinet',
    descFr: 'Armoire métallique robuste pour le rangement de documents et matériel',
    descEn: 'Robust metal cabinet for storing documents and equipment',
    priceFr: 'À partir de 150 000 FCFA',
    priceEn: 'From 150,000 FCFA',
  },
  {
    id: 'mob-2',
    image: '/images/armoire en bois.jpeg',
    category: 'furniture',
    nameFr: 'Armoire en Bois',
    nameEn: 'Wooden Cabinet',
    descFr: 'Armoire en bois élégante, idéale pour un bureau professionnel',
    descEn: 'Elegant wooden cabinet, ideal for a professional office',
    priceFr: 'À partir de 180 000 FCFA',
    priceEn: 'From 180,000 FCFA',
  },
  {
    id: 'mob-3',
    image: '/images/bureau 1 luxe 1m80.jpeg',
    category: 'furniture',
    nameFr: 'Bureau Luxe 1m80',
    nameEn: 'Luxury Desk 1.80m',
    descFr: 'Bureau de direction luxe 1m80, finition haut de gamme',
    descEn: 'Executive luxury desk 1.80m, high-end finish',
    priceFr: 'À partir de 250 000 FCFA',
    priceEn: 'From 250,000 FCFA',
  },
  {
    id: 'mob-4',
    image: '/images/bureau luxe 1m80.jpeg',
    category: 'furniture',
    nameFr: 'Bureau Luxe Angle',
    nameEn: 'Corner Luxury Desk',
    descFr: 'Bureau d\'angle luxe, maximise l\'espace de travail',
    descEn: 'Corner luxury desk, maximizes workspace',
    priceFr: 'À partir de 280 000 FCFA',
    priceEn: 'From 280,000 FCFA',
  },
  {
    id: 'mob-5',
    image: '/images/chaise 1.jpeg',
    category: 'furniture',
    nameFr: 'Chaise de Bureau Ergonomique',
    nameEn: 'Ergonomic Office Chair',
    descFr: 'Chaise de bureau ergonomique avec soutien lombaire réglable',
    descEn: 'Ergonomic office chair with adjustable lumbar support',
    priceFr: 'À partir de 45 000 FCFA',
    priceEn: 'From 45,000 FCFA',
  },
  {
    id: 'mob-6',
    image: '/images/chaise 2.jpeg',
    category: 'furniture',
    nameFr: 'Fauteuil de Direction',
    nameEn: 'Executive Armchair',
    descFr: 'Fauteuil de direction haut de gamme, cuir synthétique premium',
    descEn: 'Premium executive armchair, premium synthetic leather',
    priceFr: 'À partir de 80 000 FCFA',
    priceEn: 'From 80,000 FCFA',
  },
  {
    id: 'mob-7',
    image: '/images/chaise 3.jpeg',
    category: 'furniture',
    nameFr: 'Chaise de Travail',
    nameEn: 'Work Chair',
    descFr: 'Chaise de travail confortable avec assise rembourrée',
    descEn: 'Comfortable work chair with padded seat',
    priceFr: 'À partir de 35 000 FCFA',
    priceEn: 'From 35,000 FCFA',
  },
  {
    id: 'mob-8',
    image: '/images/chaise 4.jpeg',
    category: 'furniture',
    nameFr: 'Chaise Visiteur',
    nameEn: 'Visitor Chair',
    descFr: 'Chaise visiteur élégante pour salles de réunion et accueil',
    descEn: 'Elegant visitor chair for meeting rooms and reception',
    priceFr: 'À partir de 25 000 FCFA',
    priceEn: 'From 25,000 FCFA',
  },
  {
    id: 'mob-9',
    image: '/images/chaise 5 banquette 3 places.jpeg',
    category: 'furniture',
    nameFr: 'Banquette 3 Places',
    nameEn: '3-Seater Bench',
    descFr: 'Banquette salle d\'attente 3 places, confortable et robuste',
    descEn: 'Comfortable and robust 3-seater waiting room bench',
    priceFr: 'À partir de 65 000 FCFA',
    priceEn: 'From 65,000 FCFA',
  },
  {
    id: 'mob-10',
    image: '/images/table de bureau 1.jpeg',
    category: 'furniture',
    nameFr: 'Table de Bureau Classique',
    nameEn: 'Classic Office Table',
    descFr: 'Table de bureau classique et fonctionnelle pour tous les espaces',
    descEn: 'Classic and functional office table for all spaces',
    priceFr: 'À partir de 60 000 FCFA',
    priceEn: 'From 60,000 FCFA',
  },
  {
    id: 'mob-11',
    image: '/images/table de bureau 2.jpeg',
    category: 'furniture',
    nameFr: 'Table de Bureau Moderne',
    nameEn: 'Modern Office Table',
    descFr: 'Table de bureau au design moderne avec rangements intégrés',
    descEn: 'Modern office table with integrated storage',
    priceFr: 'À partir de 75 000 FCFA',
    priceEn: 'From 75,000 FCFA',
  },
  {
    id: 'mob-12',
    image: '/images/table de bureau 3.jpeg',
    category: 'furniture',
    nameFr: 'Table de Réunion',
    nameEn: 'Meeting Table',
    descFr: 'Table de réunion pour salles de conférence, 6 à 10 personnes',
    descEn: 'Conference room meeting table, seats 6 to 10 people',
    priceFr: 'À partir de 200 000 FCFA',
    priceEn: 'From 200,000 FCFA',
  },
  {
    id: 'mob-13',
    image: '/images/table de bureau 4.jpeg',
    category: 'furniture',
    nameFr: 'Table de Bureau Premium',
    nameEn: 'Premium Office Table',
    descFr: 'Table de bureau premium avec plateau en verre trempé',
    descEn: 'Premium office table with tempered glass top',
    priceFr: 'À partir de 120 000 FCFA',
    priceEn: 'From 120,000 FCFA',
  },
  {
    id: 'mob-14',
    image: '/images/table de bureau 5.jpg',
    category: 'furniture',
    nameFr: 'Table de Bureau Compact',
    nameEn: 'Compact Office Table',
    descFr: 'Table de bureau compacte idéale pour les petits espaces',
    descEn: 'Compact office table ideal for small spaces',
    priceFr: 'À partir de 50 000 FCFA',
    priceEn: 'From 50,000 FCFA',
  },
  {
    id: 'mob-15',
    image: '/images/table de bureau 6.jpeg',
    category: 'furniture',
    nameFr: 'Table Informatique',
    nameEn: 'Computer Desk',
    descFr: 'Table informatique avec glissière pour clavier et support moniteur',
    descEn: 'Computer desk with keyboard tray and monitor support',
    priceFr: 'À partir de 70 000 FCFA',
    priceEn: 'From 70,000 FCFA',
  },
  {
    id: 'mob-16',
    image: '/images/table de bureau 7.jpeg',
    category: 'furniture',
    nameFr: 'Bureau d\'Angle',
    nameEn: 'Corner Desk',
    descFr: 'Bureau d\'angle spacieux, optimal pour les grands espaces de travail',
    descEn: 'Spacious corner desk, optimal for large workspaces',
    priceFr: 'À partir de 95 000 FCFA',
    priceEn: 'From 95,000 FCFA',
  },
  {
    id: 'mob-17',
    image: '/images/table de bureau 8.jpeg',
    category: 'furniture',
    nameFr: 'Table de Bureau Double',
    nameEn: 'Double Office Table',
    descFr: 'Table de bureau double face pour open space et coworking',
    descEn: 'Double-sided office table for open spaces and coworking',
    priceFr: 'À partir de 140 000 FCFA',
    priceEn: 'From 140,000 FCFA',
  },
];

/**
 * Filtre les produits selon un texte de recherche (FR ou EN)
 * et une catégorie active
 */
export function filterProducts(products, searchText, activeCategoryKey, lang = 'fr') {
  const query = searchText.toLowerCase().trim();

  return products.filter((product) => {
    // Filtre catégorie
    const matchCat =
      activeCategoryKey === 'all' || product.category === activeCategoryKey;

    if (!matchCat) return false;
    if (!query) return true;

    const name = lang === 'fr' ? product.nameFr : product.nameEn;
    const desc = lang === 'fr' ? product.descFr : product.descEn;
    const catData = CATEGORIES[product.category];

    // Recherche dans le nom, la description
    const matchName = name.toLowerCase().includes(query);
    const matchDesc = desc.toLowerCase().includes(query);

    // Recherche dans les mots-clés de la catégorie
    const keywords = lang === 'fr' ? catData.searchKeywordsFr : catData.searchKeywordsEn;
    const matchKeyword = keywords.some((kw) => kw.includes(query) || query.includes(kw));

    return matchName || matchDesc || matchKeyword;
  });
}

/** Image représentative de chaque catégorie (pour CategoriesSection) */
export const CATEGORY_IMAGES = {
  computers: '/images/ordinateur 1.jpeg',
  printers: '/images/imprimente 1.jpeg',
  accessories: '/images/souris bluetooth rechargable.jpeg',
  stationery: '/images/classeur chrono.jpeg',
  furniture: '/images/chaise 2.jpeg',
};
